/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PendataanBarangMasuk;

import connection.DBConnect;
import javax.swing.JOptionPane;

/**
 *
 * @author Polman
 */
public class InputIdCargo extends javax.swing.JFrame {

    /**
     * Creates new form InputIdCargo
     */
    private DBConnect connection = new DBConnect();
    private String id_cargo = "";
    private String nomor_registrasi = "";
    private String nomor_penerbangan = "";
    private boolean sampai;
    private boolean belum = false;
    
    public InputIdCargo() {
        initComponents();
    }
    
    public InputIdCargo(boolean sampai) {
        this.sampai = sampai;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid_cargo = new javax.swing.JTextField();
        btnLanjutkan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Cargo Manifest");

        btnLanjutkan.setText("Lanjutkan");
        btnLanjutkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutkanActionPerformed(evt);
            }
        });

        btnBatal.setText("Kembali");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(btnLanjutkan))
                            .addComponent(txtid_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnLanjutkan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtid_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLanjutkan)
                    .addComponent(btnBatal))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanjutkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutkanActionPerformed
        // TODO add your handling code here:
        if(!txtid_cargo.getText().equals("") && getData()){
            if(belum){
                id_cargo = txtid_cargo.getText();
                Object[] options = {"Konfirmasi",
                    "Batal"};
                int n;
                int i;
                penjemputan:
                {
                    String in;
                    if(sampai){
                        in = "SAMPAI";
                        i = 0;
                    }else{
                        in = "GAGAL";
                        i = -1;
                    }
                    n = JOptionPane.showOptionDialog(this,
                            "Konfirmasi "+in+" cargo masuk untuk ID\n"
                            + "ID Cargo          : " + id_cargo
                          + "\nNo Registrasi     : " + nomor_registrasi
                          + "\nNo Penerbangan    : " + nomor_penerbangan,
                            "Pertanyaan",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            options,
                            options[1]);
                }
                if (n == 0){
                    updateCargoStatus(i);
                }
                else{
                    JOptionPane.showMessageDialog(this,
                            "Batal!");
                }
            }else{
                JOptionPane.showMessageDialog(this,
                        id_cargo+" sudah terkonfirmasi!");
            }
            
        }
    }//GEN-LAST:event_btnLanjutkanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed
    private void updateCargoStatus(int i){
        DBConnect connection = new DBConnect();
        try {

            String query;
            if(i == 0){
                query = "UPDATE CargoManifest SET status='Sampai' WHERE id_cargo_manifest=?";
            }else{
                query = "UPDATE CargoManifest SET status='Gagal' WHERE id_cargo_manifest=?";
            }    
            
                connection.pstat = connection.conn.prepareStatement(query);
                connection.pstat.setString(1, id_cargo);
                connection.pstat.executeUpdate();
                //connection.result.close();

                JOptionPane.showMessageDialog(this, "Konfirmasi berhasil");
            }
            catch (Exception e) {
                System.out.println("Terjadi error saat update status cargo: " + e.toString());
            }
        this.dispose();
    }
    private boolean getData(){
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select nomor_registrasi, nomor_penerbangan, status from CargoManifest where id_cargo_manifest = '"+txtid_cargo.getText()+"'";
                connection.result = connection.stat.executeQuery(query);
                int i = 0;
                while (connection.result.next()) {
                    i++;
                    nomor_registrasi = (connection.result.getString("nomor_registrasi"));
                    nomor_penerbangan = (connection.result.getString("nomor_penerbangan"));
                    String n = (String) (connection.result.getString("status"));
                    if(n.equals("Belum")){
                        belum = true;
                    }else{
                        belum = false;
                    }
                }
                connection.stat.close();
                connection.result.close();
                if(i==0){
                    return false;
                }else{
                    return true;
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error saat getData!!\n" + e.toString());
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputIdCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputIdCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputIdCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputIdCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputIdCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLanjutkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtid_cargo;
    // End of variables declaration//GEN-END:variables
}
