/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KantorCabang;

import MainMenu.MainMenu;
import connection.DBConnect;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harvianti Putri
 */
public class TambahKantorCabang extends javax.swing.JFrame {
    DBConnect connection = new DBConnect();
    
    String kode_kantor_cabang;
    String nama_kantor;
    String telepon;
    String alamat;
    String provinsi;
    String kotakab;
    /**
     * Creates new form TambahKantorCabang
     */
    public TambahKantorCabang() {
        initComponents();
       // model = new DefaultTableModel();
     
        txtKodeKC.setText("KC-"+getLastID());
    }
    
     private void clear()
    {
        txtKodeKC.setText("");
        txtNamaKC.setText("");
        txtTeleponKC.setText("");
        txtAlamatKC.setText("");
        txtProvinsi.setText("");
        txtKotaKab.setText("");
    }
     
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaKC = new javax.swing.JTextField();
        txtTeleponKC = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtKodeKC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatKC = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProvinsi = new javax.swing.JTextField();
        txtKotaKab = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Kantor Cabang");

        jLabel2.setText("Kode Kantor Cabang");

        jLabel3.setText("Nama Kantor Cabang");

        jLabel4.setText("Telepon");

        jLabel5.setText("Alamat");

        txtNamaKC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKCKeyTyped(evt);
            }
        });

        txtTeleponKC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTeleponKCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTeleponKCKeyTyped(evt);
            }
        });

        btnTambah.setText("Tambah");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        txtKodeKC.setEditable(false);

        txtAlamatKC.setColumns(20);
        txtAlamatKC.setRows(5);
        jScrollPane1.setViewportView(txtAlamatKC);

        jLabel6.setText("Provinsi");

        jLabel7.setText("Kota/Kabupaten");

        txtProvinsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvinsiKeyTyped(evt);
            }
        });

        txtKotaKab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKotaKabKeyTyped(evt);
            }
        });

        jButton1.setText("Batal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodeKC, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNamaKC)
                                        .addComponent(txtTeleponKC, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(111, 111, 111)
                        .addComponent(btnSimpan)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSimpan, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnTambah))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnUbah))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKodeKC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtNamaKC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtTeleponKC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKotaKab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(jButton1)
                    .addComponent(btnKembali))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String getLastID(){
        String kode_kantor_cabang = null;
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select count(kode_kantor_cabang) Total from KantorCabang";
                connection.result = connection.stat.executeQuery(query);
                int count = 0;
                while (connection.result.next()) {
                    
                    count = Integer.parseInt(connection.result.getString("total"));
                    }
                connection.stat.close();
                connection.result.close();
                count++;
                
            if(Integer.toString(count).length() == 1)
            {
                kode_kantor_cabang = "000" + count;
            }
            else if (Integer.toString(count).length() == 2)
            {
                kode_kantor_cabang =  "00" + count;
            }
            else if (Integer.toString(count).length() == 3)
            {
                kode_kantor_cabang = "0" + count;
            }
            else
            {
                kode_kantor_cabang = Integer.toString(count);
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        return String.valueOf(kode_kantor_cabang);
    }

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        kode_kantor_cabang = txtKodeKC.getText();
        nama_kantor = txtNamaKC.getText();
        telepon = txtTeleponKC.getText();
        alamat = txtAlamatKC.getText();
        provinsi = txtProvinsi.getText();
        kotakab = txtKotaKab.getText();
        
        if(kode_kantor_cabang.equals("")|| nama_kantor.equals("")|| telepon.equals("") || alamat.equals("")|| provinsi.equals("") || kotakab.equals("")){
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
        }
        else
        {
            
        
        //untuk memasukkan dalam ke dalam database
        try
        {
            String query = "INSERT INTO KantorCabang VALUES (?,?,?,?,?,?)";
            connection.pstat = connection.conn.prepareStatement(query);
            connection.pstat.setString(1, kode_kantor_cabang);
            connection.pstat.setString(2, nama_kantor);
            connection.pstat.setString(3, telepon);
            connection.pstat.setString(4, alamat);
            connection.pstat.setString(5, provinsi);
            connection.pstat.setString(6, kotakab);
            
            //insert ke dalam database
            connection.pstat.executeUpdate();
            //menutup koneksi database
            connection.pstat.close();
            
        }catch (Exception e){
             System.out.println("Terjadi error pada saat insert data kantor cabang :" + e);
            clear();
        }
        JOptionPane.showMessageDialog(this, "insert data kantor cabang berhasil");
        clear();
        txtKodeKC.setText("KC-"+getLastID());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        UbahKantorCabang ubahkc = new UbahKantorCabang();
        ubahkc.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtTeleponKCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleponKCKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponKCKeyPressed

    private void txtNamaKCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKCKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKCKeyPressed

    private void txtNamaKCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKCKeyTyped
        // TODO add your handling code here:
          char enter = evt.getKeyChar();
            if(!Character.isLetter(enter) && !Character.isISOControl(enter) && !Character.isWhitespace(enter)){
                evt.consume();
            }
    }//GEN-LAST:event_txtNamaKCKeyTyped

    private void txtTeleponKCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleponKCKeyTyped
        // TODO add your handling code here:
          char enter = evt.getKeyChar();
            if(txtTeleponKC.getText().length()==13){
            evt.consume();
            }
    }//GEN-LAST:event_txtTeleponKCKeyTyped

    private void txtProvinsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvinsiKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
            if(!Character.isLetter(enter) && !Character.isISOControl(enter) && !Character.isWhitespace(enter)){
                evt.consume();
            }
    }//GEN-LAST:event_txtProvinsiKeyTyped

    private void txtKotaKabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKotaKabKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
            if(!Character.isLetter(enter) && !Character.isISOControl(enter) && !Character.isWhitespace(enter)){
                evt.consume();
            }
    }//GEN-LAST:event_txtKotaKabKeyTyped

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        MainMenu main = new MainMenu();
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahKantorCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahKantorCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahKantorCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahKantorCabang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahKantorCabang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlamatKC;
    private javax.swing.JTextField txtKodeKC;
    private javax.swing.JTextField txtKotaKab;
    private javax.swing.JTextField txtNamaKC;
    private javax.swing.JTextField txtProvinsi;
    private javax.swing.JTextField txtTeleponKC;
    // End of variables declaration//GEN-END:variables
}
