/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TransaksiPengirimanBarang;

import MainMenu.Login;
import MainMenu.MainMenuStaff;
import MainMenu.MainMenuStaffKirim;
import connection.DBConnect;
import java.sql.SQLException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * (-) Belum memunculkan data barang berdasarkan kantor yang log in
 * @author user
 */
public class CekDoc extends javax.swing.JFrame {

    /**
     * Creates new form CekDoc
     */
    private String id_pemesanan="";
    private String id_connote="";
    private String KantorCabang = "KMF JKT";
    
    public CekDoc() {
        initComponents();
        model = new DefaultTableModel();
        addColomn();
        tblList.setModel(model);
        liatdata();
    }
    
    public CekDoc(String kantorCabang) {
        initComponents();
        this.KantorCabang = kantorCabang;
        model = new DefaultTableModel();
        addColomn();
        tblList.setModel(model);
        liatdata();
    }
    DefaultTableModel model;
    public void addColomn() {
        model.addColumn("ID Connote");
        model.addColumn("ID Pemesanan");
        model.addColumn("Jenis Barang");
        model.addColumn("Berat Barang");
        model.addColumn("Nama Penerima");
        model.addColumn("Alamat Penerima");
        model.addColumn("Kota Penerima");
        model.addColumn("No Telphone Penerima");
        model.addColumn("Total harga");
        model.addColumn("Keterangan Pembayaran");
    }
    private String getIDKantor(String in) {
        DBConnect connection = new DBConnect();
        try {
            connection.stat = connection.conn.createStatement();
            String query = "select kode_kantor_cabang from KantorCabang where nama_kantor = '" + in + "'";
            connection.result = connection.stat.executeQuery(query);
            String output = null;
            while (connection.result.next()) {

                output = (connection.result.getString("kode_kantor_cabang"));

            }
            connection.stat.close();
            connection.result.close();
            return output;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!!\n" + e.toString());
        }
        return null;
    }
    public void liatdata(){
        model.getDataVector().removeAllElements();

        model.fireTableDataChanged();
        try{
            DBConnect c = new DBConnect();
            c.stat = c.conn.createStatement();
            String sql = "SELECT * FROM Connote join DataBarangPelanggan  on Connote.id_pemesanan = DataBarangPelanggan.id_pemesanan and DataBarangPelanggan.status_barang != 'Barang siap diberangkat' and Connote.status_pengiriman = 'Belum' and DataBarangPelanggan.kode_kantor_cabang = '"+getIDKantor(KantorCabang).toString()+"'";
            c.result = c.stat.executeQuery(sql);
            
            while (c.result.next()) {
                    Object[] obj = new Object[10];
                    obj[0] = c.result.getString("id_connote");
                    obj[1] = c.result.getString("id_pemesanan");
                    obj[2] = c.result.getString("jenis_barang");
                    obj[3] = c.result.getString("berat_barang");
                    obj[4] = c.result.getString("nama_penerima");
                    obj[5] = c.result.getString("alamat_penerima");
                    obj[6] = c.result.getString("kota_penerima");
                    obj[7] = c.result.getString("no_telphone_penerima");
                    obj[8] = c.result.getString("total_harga");
                    obj[9] = c.result.getString("keterangan_pembayaran");

                    model.addRow(obj);

            }
            c.stat.close();
            c.result.close();  
        } catch (SQLException ex){
            System.out.println("Terjadi error"+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnKomen = new javax.swing.JButton();
        btnSesuai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKomen = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblcek = new javax.swing.JLabel();
        lblsortir = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblbagg = new javax.swing.JLabel();
        lbldatacar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setSize(new java.awt.Dimension(1200, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 700));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("List Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnKembali.setBackground(new java.awt.Color(204, 255, 204));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnKomen.setBackground(new java.awt.Color(204, 255, 204));
        btnKomen.setText("Komentar");
        btnKomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomenActionPerformed(evt);
            }
        });

        btnSesuai.setBackground(new java.awt.Color(204, 255, 204));
        btnSesuai.setText("Sesuai");
        btnSesuai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesuaiActionPerformed(evt);
            }
        });

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblList);

        txtKomen.setBackground(new java.awt.Color(204, 204, 255));
        txtKomen.setColumns(20);
        txtKomen.setRows(5);
        jScrollPane1.setViewportView(txtKomen);

        jLabel2.setText("Komentar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(300, 300, 300)
                        .addComponent(btnKomen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                        .addComponent(btnSesuai))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnKomen)
                    .addComponent(btnSesuai))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(240, 700));

        lblcek.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblcek.setForeground(new java.awt.Color(255, 255, 255));
        lblcek.setText("Cek Connote");
        lblcek.setToolTipText("");
        lblcek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcekMouseClicked(evt);
            }
        });

        lblsortir.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblsortir.setForeground(new java.awt.Color(255, 255, 255));
        lblsortir.setText("Sortir Barang");
        lblsortir.setToolTipText("");
        lblsortir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsortirMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Keluar");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        lblbagg.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblbagg.setForeground(new java.awt.Color(255, 255, 255));
        lblbagg.setText("Bagging Barang");
        lblbagg.setToolTipText("");
        lblbagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbaggMouseClicked(evt);
            }
        });

        lbldatacar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbldatacar.setForeground(new java.awt.Color(255, 255, 255));
        lbldatacar.setText("Data Cargo Manifest");
        lbldatacar.setToolTipText("");
        lbldatacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldatacarMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainMenu/b.png"))); // NOI18N
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldatacar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsortir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbagg)
                            .addComponent(lblcek, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(lblcek, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblsortir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblbagg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lbldatacar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        MainMenuStaffKirim MainMenuStaffKirim = new MainMenuStaffKirim();
        this.setVisible(false);
        MainMenuStaffKirim.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSesuaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesuaiActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Dengan menekan Yes anda menyatakan barang ini sesuai", "Pertanyaan", JOptionPane.YES_NO_CANCEL_OPTION)!=JOptionPane.YES_OPTION){
            return;
        }
        DBConnect connection = new DBConnect();
        try {
                
                String query = "UPDATE DataBarangPelanggan SET status_barang = 'Barang siap diberangkatkan' WHERE id_pemesanan=?";
                //System.out.println(query);
                connection.pstat = connection.conn.prepareStatement(query);
                connection.pstat.setString(1, id_pemesanan);

                connection.pstat.executeUpdate();
                connection.pstat.close();
                addRiwayat("Barang siap diberangkatkan");
                JOptionPane.showMessageDialog(this, "Data barang telah sesuai");
            }
        catch (SQLException e) {
            System.out.println("Terjadi error saat btnSesuaiActionPerformed: " + e.toString());
        }
       liatdata(); 
    }//GEN-LAST:event_btnSesuaiActionPerformed
    private void addRiwayat(String riwayat){
        Format formatter = new SimpleDateFormat("yyyyMMdd");
        Format formatterTime = new SimpleDateFormat("hh:mm:ss");
        
            try
            {
                DBConnect c = new DBConnect();
                String query = "INSERT INTO Riwayat VALUES (?,?,?,?)";
                     c.pstat = c.conn.prepareStatement(query);
                     c.pstat.setString(1, formatter.format(new Date()));
                     c.pstat.setString(2, formatterTime.format(new Date()));
                     c.pstat.setString(3, riwayat);
                     c.pstat.setString(4, id_pemesanan);

                      //insert ke dalam database
                c.pstat.executeUpdate();
                c.pstat.close();
                //JOptionPane.showMessageDialog(this, "insert data Baggin berhasil");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Terjadi error pada saat addRiwayat :" + e);
            }        
    }
    private void ubahStatusGagal(){
        DBConnect connection = new DBConnect();
        try {
                
                String query = "UPDATE Connote SET status_pengiriman = 'Gagal' WHERE id_connote=?";
                //System.out.println(query);
                connection.pstat = connection.conn.prepareStatement(query);
                connection.pstat.setString(1, id_connote);

                connection.pstat.executeUpdate();
                connection.pstat.close();
            }
        catch (SQLException e) {
            System.out.println("Terjadi error saat menambahkan komentar: " + e.toString());
        }
        liatdata();
    }
    private void btnKomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomenActionPerformed
        // TODO add your handling code here:
//        CommentCek Comment = new CommentCek();
//        this.setVisible(true);
//        Comment.setVisible(true);
        if(JOptionPane.showConfirmDialog(this, "Dengan menekan Yes anda menyatakan barang ini tidak sesuai", "Pertanyaan", JOptionPane.YES_NO_CANCEL_OPTION)!=JOptionPane.YES_OPTION){
            return;
        }
        
        //System.out.println(id_pemesanan);
        DBConnect connection = new DBConnect();
        try {
                
                String query = "UPDATE DataBarangPelanggan SET status_barang = ? WHERE id_pemesanan=?";
                //System.out.println(query);
                connection.pstat = connection.conn.prepareStatement(query);
                connection.pstat.setString(1, txtKomen.getText());
                connection.pstat.setString(2, id_pemesanan);

                connection.pstat.executeUpdate();
                connection.pstat.close();
                addRiwayat(txtKomen.getText());
                JOptionPane.showMessageDialog(this, "Menambah komentar berhasil");
                ubahStatusGagal();
            }
            catch (SQLException e) {
                System.out.println("Terjadi error saat menambahkan komentar: " + e.toString());
            }
        
    }//GEN-LAST:event_btnKomenActionPerformed
    
    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        // TODO add your handling code here:
        int i = tblList.getSelectedRow();
        
        if(i != -1){
            id_pemesanan = tblList.getValueAt(i, 1).toString();
            id_connote = tblList.getValueAt(i, 0).toString();
        }
        
        JOptionPane.showMessageDialog(this,id_connote +" Dipilih");
    }//GEN-LAST:event_tblListMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void lblcekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcekMouseClicked
        CekDoc c = new CekDoc(KantorCabang);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblcekMouseClicked

    private void lblsortirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsortirMouseClicked
        Sortir s = new Sortir(KantorCabang);
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblsortirMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        MainMenuStaff t= new MainMenuStaff(KantorCabang);
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblbaggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbaggMouseClicked
        Bagging bag = new Bagging(KantorCabang);
        bag.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblbaggMouseClicked

    private void lbldatacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldatacarMouseClicked
        listBagging bag = new listBagging(KantorCabang);
        this.setVisible(false);
        bag.setVisible(true);
    }//GEN-LAST:event_lbldatacarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKomen;
    private javax.swing.JButton btnSesuai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblbagg;
    private javax.swing.JLabel lblcek;
    private javax.swing.JLabel lbldatacar;
    private javax.swing.JLabel lblsortir;
    private javax.swing.JTable tblList;
    private javax.swing.JTextArea txtKomen;
    // End of variables declaration//GEN-END:variables
}
