/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import CS.tambahCS;
import CS.ubahCS;
import JenisPaket.TambahJenisPaket;
import Departemen.TambahDepartemen;
import Departemen.UbahDepartemen;
import Driver.CreateDriver;
import Driver.UbahDriver;
import JenisPaket.UbahJenisPaket;
import KantorCabang.TambahKantorCabang;
import KantorCabang.UbahKantorCabang;
import Staff.Staff;
import Staff.Ubah_Staff;
import Pelanggan.Pelanggan;

/**
 *
 * @author putri ramadani rais
 */
public class MainMenuStaffKelola extends javax.swing.JFrame {

    boolean ubah; //tambah . ubah
    boolean olah=false;
    String KantorCabang;
  
    /**
     * Creates new form MainMenuStaffKelola
     */
    public MainMenuStaffKelola() {
        initComponents();
        
        btnUbahData.setVisible(false);
        btnTambahData.setVisible(false);
        panelCreate.setVisible(false);
    }
    
    public MainMenuStaffKelola(String KantorCabang) {
        initComponents();
        
        this.KantorCabang = KantorCabang;
        btnUbahData.setVisible(false);
        btnTambahData.setVisible(false);
        panelCreate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnUbahData = new javax.swing.JButton();
        btnTambahData = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        panelCreate = new javax.swing.JPanel();
        btnDepartment = new javax.swing.JButton();
        btnJnsPaket = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnCS = new javax.swing.JButton();
        btnKC = new javax.swing.JButton();
        btnOlahData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnUbahData.setText("Ubah Data");
        btnUbahData.setInheritsPopupMenu(true);
        btnUbahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDataActionPerformed(evt);
            }
        });

        btnTambahData.setText("Tambah Data");
        btnTambahData.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        btnKembali.setText("kembali");
        btnKembali.setInheritsPopupMenu(true);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        panelCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCreate.setToolTipText("");

        btnDepartment.setText("Master Departemen");
        btnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentActionPerformed(evt);
            }
        });

        btnJnsPaket.setText("Master Jenis Paket");
        btnJnsPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJnsPaketActionPerformed(evt);
            }
        });

        btnPelanggan.setText("Master Pelanggan");
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        btnDriver.setText("Master Driver");
        btnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverActionPerformed(evt);
            }
        });

        btnStaff.setText("Master Staff");
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });

        btnCS.setText("Master Customer Service");
        btnCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSActionPerformed(evt);
            }
        });

        btnKC.setText("Master Kantor Cabang");
        btnKC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreateLayout = new javax.swing.GroupLayout(panelCreate);
        panelCreate.setLayout(panelCreateLayout);
        panelCreateLayout.setHorizontalGroup(
            panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCS, javax.swing.GroupLayout.PREFERRED_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnKC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDriver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJnsPaket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCreateLayout.setVerticalGroup(
            panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJnsPaket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOlahData.setText("Pegolahan Data");
        btnOlahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlahDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUbahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTambahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOlahData, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(panelCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnOlahData)
                .addGap(18, 18, 18)
                .addComponent(btnTambahData)
                .addGap(18, 18, 18)
                .addComponent(btnUbahData)
                .addGap(31, 31, 31)
                .addComponent(panelCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDataActionPerformed
        ubah = true;
        btnUbahData.setVisible(false);
        btnTambahData.setVisible(false);
        panelCreate.setVisible(true);
    }//GEN-LAST:event_btnUbahDataActionPerformed

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        ubah = false;
        panelCreate.setVisible(true);
        btnTambahData.setVisible(false);
        btnUbahData.setVisible(false);
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MainMenuStaff t= new MainMenuStaff();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentActionPerformed
        if(ubah){
            UbahDepartemen dpt = new UbahDepartemen();
            dpt.setVisible(true);
        }else{
            TambahDepartemen dpt = new TambahDepartemen();
            dpt.setVisible(true);
        }

        this.setVisible(false);
    }//GEN-LAST:event_btnDepartmentActionPerformed

    private void btnJnsPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJnsPaketActionPerformed
        if(ubah){
            UbahJenisPaket dpt = new UbahJenisPaket();
            dpt.setVisible(true);
        }else{
            TambahJenisPaket dpt = new TambahJenisPaket();
            dpt.setVisible(true);
        }

        this.setVisible(false);

    }//GEN-LAST:event_btnJnsPaketActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        Pelanggan form = new Pelanggan(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverActionPerformed
        // TODO add your handling code here:
        if(ubah){
            UbahDriver driver = new UbahDriver();
            driver.setVisible(true);
        }else{
            CreateDriver driver = new CreateDriver();
            driver.setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnDriverActionPerformed

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        // TODO add your handling code here:
        if(ubah){
            Ubah_Staff staff = new Ubah_Staff();
            staff.setVisible(true);
        }else{
            Staff staff = new Staff(KantorCabang);
            staff.setVisible(true);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSActionPerformed
        // TODO add your handling code here:
        if(ubah){
            ubahCS form = new ubahCS();
            this.setVisible(false);
            form.setVisible(true);
        }else{
            tambahCS form = new tambahCS();
            this.setVisible(false);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnCSActionPerformed

    private void btnKCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKCActionPerformed
        // TODO add your handling code here:
        if(ubah){
            UbahKantorCabang form = new UbahKantorCabang();
            this.setVisible(false);
            form.setVisible(true);
        }else{
            TambahKantorCabang form = new TambahKantorCabang();
            this.setVisible(false);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btnKCActionPerformed

    private void btnOlahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlahDataActionPerformed
        // TODO add your handling code here:
        if(olah){
            olah = false;
            panelCreate.setVisible(false);
            btnTambahData.setVisible(false);
            btnUbahData.setVisible(false);
        }else{
            olah = true;
            btnTambahData.setVisible(true);
            btnUbahData.setVisible(true);
        }
    }//GEN-LAST:event_btnOlahDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuStaffKelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuStaffKelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuStaffKelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuStaffKelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuStaffKelola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCS;
    private javax.swing.JButton btnDepartment;
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnJnsPaket;
    private javax.swing.JButton btnKC;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnOlahData;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JButton btnUbahData;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCreate;
    // End of variables declaration//GEN-END:variables
}
