/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import MainMenu.MainMenuStaffKelola;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.Format;
import java.text.SimpleDateFormat;
import connection.DBConnect;
/**
 *
 * @author SATRIA ADJIE PRAYOGA
 */
public class Staff extends javax.swing.JFrame {
    private DefaultTableModel model;
    public ResultSet rs;
    DBConnect connection = new DBConnect();
    Format formatter = new SimpleDateFormat("yyyy-MM-dd");
    String KantorCabang;
    String outputKodeKc, outputDeptId;
    /**
     * Creates new form Staff
     */
    public Staff(){
        initComponents();
        
        txtIdStaff.setText("Staff-" + getLastID());
        txtKantorCabang.setText(KantorCabang);
        model = new DefaultTableModel();
        addItemDepartemen();
        addColumn();
        loadData();
    }
    
    public Staff(String KantorCabang){
        initComponents();
        this.KantorCabang = KantorCabang;
        txtIdStaff.setText("Staff-" + getLastID());
        
        txtKantorCabang.setText(KantorCabang);
        model = new DefaultTableModel();
        addItemDepartemen();
        addColumn();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdStaff = new javax.swing.JTextField();
        DateLahir = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        txtKantorCabang = new javax.swing.JTextField();
        cbDept = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(460, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(460, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 55));
        jLabel1.setText("TAMBAH STAFF");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel4.setText("No Telp");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel5.setText("Email");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        txtNama.setBackground(new java.awt.Color(204, 204, 255));
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 167, -1));

        txtAlamat.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 167, 48));

        txtTelp.setBackground(new java.awt.Color(204, 204, 255));
        txtTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelpKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 167, -1));

        jLabel6.setText("Tanggal Lahir");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        txtEmail.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 167, -1));

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jLabel8.setText("Id Staff");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        txtIdStaff.setBackground(new java.awt.Color(204, 204, 255));
        txtIdStaff.setEnabled(false);
        txtIdStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdStaffActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 167, -1));

        DateLahir.setBackground(new java.awt.Color(204, 204, 255));
        DateLahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DateLahirKeyTyped(evt);
            }
        });
        jPanel1.add(DateLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 167, -1));

        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel9.setText("Kantor cabang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, 20));

        jLabel10.setText("Departement");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        cbStatus.setBackground(new java.awt.Color(204, 204, 255));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak aktif" }));
        jPanel1.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 170, -1));

        txtKantorCabang.setBackground(new java.awt.Color(204, 204, 255));
        txtKantorCabang.setEnabled(false);
        jPanel1.add(txtKantorCabang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 170, -1));

        cbDept.setBackground(new java.awt.Color(204, 204, 255));
        cbDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Departemen --" }));
        jPanel1.add(cbDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 170, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 120, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private String getKodeKantorCabang(String in){
        outputKodeKc= "";
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select * from KantorCabang where nama_kantor ='"+in+"'";
                connection.result = connection.stat.executeQuery(query);
                
                connection.result.next();
                    
                outputKodeKc = (connection.result.getString("kode_kantor_cabang"));
                
                
                connection.stat.close();
                connection.result.close();
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Get Kode Kc error!!\n" + e.toString());
        }
        return outputKodeKc;
    }
    
    private String getDeptID(String in){
        outputDeptId= "";
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select * from Departement where nama_dept ='"+in+"'";
                connection.result = connection.stat.executeQuery(query);
                
                connection.result.next();
                    
                outputDeptId = (connection.result.getString("id_dept"));
                
                
                connection.stat.close();
                connection.result.close();
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Get Id Dept error!!\n" + e.toString());
        }
        return outputDeptId;
    }
    
    private void addItemDepartemen(){
        cbDept.removeAll();
        try {
            
            connection.stat = connection.conn.createStatement();
            String query = "SELECT nama_dept FROM Departement";
            connection.result = connection.stat.executeQuery(query);
            connection.result.next();
            do{
                
                cbDept.addItem(connection.result.getString("nama_dept"));
            }while(connection.result.next());
            
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tambah item Departemen gagal!\n" + e.toString());
        }
    }
    
    private String getLastID(){
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select count(id_staff) Total from Staff";
                connection.result = connection.stat.executeQuery(query);
                int count = 0;
                while (connection.result.next()) {
                    
                    count = Integer.parseInt(connection.result.getString("total"));
                    }
                connection.stat.close();
                connection.result.close();
                
                
                count++;
                
                if(Integer.toString(count).length() == 1)
            {
                return "000" + count;
            }
            else if (Integer.toString(count).length() == 2)
            {
                return "00" + count;
            }
            else if (Integer.toString(count).length() == 3)
            {
                return "0" + count;
            }
            else
            {
                return Integer.toString(count);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Generate Id gagal!\n" + ex.toString());
            return null;
        }
    }
    private void txtIdStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdStaffActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        new Ubah_Staff(KantorCabang).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUbahActionPerformed
   
    public void addColumn(){
        model.addColumn("Id");
        model.addColumn("Nama Staff");
        model.addColumn("Alamat");
        model.addColumn("Tgl Lahir");
        model.addColumn("No Telp");
        model.addColumn("Email");
        model.addColumn("Status");
        model.addColumn("Kantor Cabang");
        model.addColumn("Departemen");
    }
    
    public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try{
            connection.stat = connection.conn.createStatement();
            String query = "SELECT * FROM Staff";
            connection.result = connection.stat.executeQuery(query);
            
            while(connection.result.next()){
                Object[] obj = new Object[9];
                obj[0] = connection.result.getString("id_staff");
                obj[1] = connection.result.getString("nama_staff");
                obj[2] = connection.result.getString("alamat_staff");
                obj[3] = connection.result.getString("tgl_lahir");
                obj[4] = connection.result.getString("no_telphone");
                obj[5] = connection.result.getString("email");
                obj[6] = connection.result.getString("status_aktif");
                obj[7] = connection.result.getString("kode_kantor_cabang");
                obj[8] = connection.result.getString("id_dept");
                model.addRow(obj);
            }
            connection.stat.close();
            connection.result.close();
        }catch(Exception ex){
            System.out.println("Terjadi error saat load data: " + ex);
        }
    }
    
    private void Clear(){
        txtIdStaff.setText("Staff-" + getLastID());
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");
        txtEmail.setText("");
    }
    
    private static final String EMAIL_PATTERN = 
    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String id_staff = txtIdStaff.getText();
        String nama = txtNama.getText();
        String alamat = txtAlamat.getText();
        String noTelp = txtTelp.getText();
        String tglLahir = formatter.format(DateLahir.getDate());
        String email = txtEmail.getText();
        String status = (String)cbStatus.getSelectedItem();
        String Kc = txtKantorCabang.getText();
        String Dept = (String)cbDept.getSelectedItem();
        getKodeKantorCabang(Kc);
        getDeptID(Dept);
        
        if(id_staff.equals("")||nama.equals("")||alamat.equals("")||tglLahir.equals("")||noTelp.equals("")||email.equals("")){
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
        }
        else
        {
            if (!email.matches(EMAIL_PATTERN)) {
                JOptionPane.showMessageDialog(this, "Format email salah");
            }
            else{
                getKodeKantorCabang(Kc);
                try {
                String query = ("INSERT INTO Staff VALUES(?,?,?,?,?,?,?,?,?)");
                connection.pstat = connection.conn.prepareStatement(query);
                connection.pstat.setString(1, id_staff);
                connection.pstat.setString(2, nama);
                connection.pstat.setString(3, alamat);
                connection.pstat.setString(4, tglLahir);
                connection.pstat.setString(5, noTelp);
                connection.pstat.setString(6, email);
                connection.pstat.setString(7, status);
                connection.pstat.setString(8, outputKodeKc);
                connection.pstat.setString(9, outputDeptId);

                connection.pstat.executeUpdate();
                connection.pstat.close();
                JOptionPane.showMessageDialog(this, "Insert data staff berhasil");
                Clear();
                loadData();
                }
                catch(Exception e) {
                    System.out.println("Terjadi error saat insert ke database: " + e);
                }
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
            if(!Character.isLetter(enter) && !Character.isISOControl(enter) && !Character.isWhitespace(enter)){
                evt.consume();
            }
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
            if(!Character.isLetter(enter) && !Character.isISOControl(enter) && !Character.isWhitespace(enter)){
                evt.consume();
            }
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtTelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
            if(!Character.isDigit(enter)){
                evt.consume();
            }
            
            if(txtTelp.getText().length()==13){
                evt.consume();
            }
    }//GEN-LAST:event_txtTelpKeyTyped

    private void DateLahirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateLahirKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_DateLahirKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateLahir;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbDept;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdStaff;
    private javax.swing.JTextField txtKantorCabang;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
