/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver;

import MainMenu.MainMenuStaffKelola;
import connection.DBConnect;
import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Polman
 */
public class CreateDriver extends javax.swing.JFrame {

    /**
     * Creates new form CreateDriver
     */
    private boolean dariubah = false;
    
    private static final String EMAIL_PATTERN = 
    "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    private String KantorCabang = "";
    public CreateDriver() {
        initComponents();
        txtid_driver.setText("DRV-"+getLastID());
    }
    
    public CreateDriver(String kantorCabang) {
        initComponents();
        txtid_driver.setText("DRV-"+getLastID());
        this.KantorCabang = kantorCabang;
        txtKantorCabang.setText(kantorCabang);
    }
    
    public CreateDriver(String kantorCabang, boolean in) {
        initComponents();
        dariubah = in;
        txtid_driver.setText("DRV-"+getLastID());
        this.KantorCabang = kantorCabang;
        txtKantorCabang.setText(kantorCabang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtno_telepon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        txtid_driver = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        txtnama_driver = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtKantorCabang = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttanggal_lahir = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnKembali1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(460, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("No Telepon");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        txtno_telepon.setBackground(new java.awt.Color(204, 204, 255));
        txtno_telepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtno_teleponKeyTyped(evt);
            }
        });
        jPanel1.add(txtno_telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 200, -1));

        jLabel2.setText("ID Driver");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        txtEmail.setBackground(new java.awt.Color(204, 204, 255));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 200, -1));

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        btnBatal.setBackground(new java.awt.Color(204, 255, 204));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 69, -1));

        txtid_driver.setText("Generate");
        jPanel1.add(txtid_driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        btnSimpan.setBackground(new java.awt.Color(204, 255, 204));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        txtnama_driver.setBackground(new java.awt.Color(204, 204, 255));
        txtnama_driver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnama_driverKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnama_driverKeyTyped(evt);
            }
        });
        jPanel1.add(txtnama_driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 200, -1));

        jLabel8.setText("kantor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        txtAlamat.setBackground(new java.awt.Color(204, 204, 255));
        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 90));

        txtKantorCabang.setText("KantorCabang");
        jPanel1.add(txtKantorCabang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabel5.setText("Tanggal Lahir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        txttanggal_lahir.setBackground(new java.awt.Color(204, 204, 255));
        txttanggal_lahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttanggal_lahirKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttanggal_lahirKeyTyped(evt);
            }
        });
        jPanel1.add(txttanggal_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(113, 450));

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnKembali1.setText("Kembali");
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(btnKembali1)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 55));
        jLabel1.setText("Tambah Driver");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        boolean benar = true;
        if(txtnama_driver.getText().equals("") || txtAlamat.getText().equals("") || txttanggal_lahir.getDateFormatString().equals("") || txtno_telepon.getText().equals("")){
                JOptionPane.showMessageDialog(this,
                        "Masukkan data dengan benar!");
                benar = false;
        }else{
            if (!txtEmail.getText().matches(EMAIL_PATTERN)) {
            benar = false;
            JOptionPane.showMessageDialog(this,
                        "Masukkan email dengan benar!");
        }
        }
        if(benar){
            Format formatter = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
            String tanggal = formatter.format(txttanggal_lahir.getDate());
            Object[] options = {"Yaa, simpan",
                "Tidak, batal"};
            int n;
            penjemputan:
            {
                n = JOptionPane.showOptionDialog(this,
                        "Periksa data sebelum disimpan\n"
                        + "ID Driver     : " + txtid_driver.getText()
                        + "\nNama          : " + txtnama_driver.getText()
                        + "\nAlamat        : " + txtAlamat.getText()
                        + "\nTanggal Lahir : " + tanggal
                        + "\nNo Telepon    : " + txtno_telepon.getText()
                        + "\nEmail         : " + txtEmail.getText()
                        + "\nKantor        : " + txtKantorCabang.getText(),
                        "Pertanyaan",
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[1]);
            }
            if (n == 0) {
                inputDriver();
            } else if (n == 1) {
                JOptionPane.showMessageDialog(this,
                        "Batal!");
            }
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtnama_driverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnama_driverKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnama_driverKeyPressed

    private void txtnama_driverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnama_driverKeyTyped
        // TODO add your handling code here:
        if(txtnama_driver.getText().length()==25){
            evt.consume();
        }else{
            char enter = evt.getKeyChar();
            if(!Character.isLetter(enter) && !Character.isISOControl(enter) && !Character.isWhitespace(enter)){
                evt.consume();
                
            }
        }
    }//GEN-LAST:event_txtnama_driverKeyTyped

    private void txtAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyTyped
        // TODO add your handling code here:
        if(txtAlamat.getText().length()==50){
            evt.consume();
        }
    }//GEN-LAST:event_txtAlamatKeyTyped

    private void txtno_teleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtno_teleponKeyTyped
        // TODO add your handling code here:
        if(txtno_telepon.getText().length()==13){
            evt.consume();
        }else{
            char enter = evt.getKeyChar();
            if(!Character.isDigit(enter) && !Character.isISOControl(enter)){
                evt.consume();
            }
        }
        
    }//GEN-LAST:event_txtno_teleponKeyTyped

    
    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        if(txtEmail.getText().length()==13){
            evt.consume();
        }else{
            
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txttanggal_lahirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttanggal_lahirKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttanggal_lahirKeyTyped

    private void txttanggal_lahirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttanggal_lahirKeyPressed
        // TODO add your handling code here:
      txttanggal_lahir.setDate(null);
    }//GEN-LAST:event_txttanggal_lahirKeyPressed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(dariubah){
            UbahDriver i = new UbahDriver(KantorCabang);
            i.setVisible(true);
        }else{
            MainMenuStaffKelola m = new MainMenuStaffKelola(KantorCabang);
            m.setVisible(true);
        }
        
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        UbahDriver dpt = new UbahDriver(KantorCabang);
        dpt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnKembali1ActionPerformed
    private String getLastID(){
        DBConnect connection = new DBConnect();
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select count(ID_Staff) Total from Driver";
                connection.result = connection.stat.executeQuery(query);
                int count = 0;
                while (connection.result.next()) {
                    
                    count = Integer.parseInt(connection.result.getString("total"));
                    }
                connection.stat.close();
                connection.result.close();
                
                
                count++;
                
                if(Integer.toString(count).length() == 1)
            {
                return "000" + count;
            }
            else if (Integer.toString(count).length() == 2)
            {
                return "00" + count;
            }
            else if (Integer.toString(count).length() == 3)
            {
                return "0" + count;
            }
            else
            {
                return Integer.toString(count);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error!!\n" + e.toString());
        }
        return null;
    }
    private String getDeptID(String in){
        DBConnect connection = new DBConnect();
        String output= "";
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select * from Departement where nama_dept ='"+in+"'";
                connection.result = connection.stat.executeQuery(query);
                
                connection.result.next();
                    
                output = (connection.result.getString("id_dept"));
                
                
                connection.stat.close();
                connection.result.close();
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error!!\n" + e.toString());
        }
        return output;
    }
    private String getKodeKantorCabang(String in){
        DBConnect connection = new DBConnect();
        String output= "";
        try{
            connection.stat = connection.conn.createStatement();
                String query = "select * from KantorCabang where nama_kantor ='"+in+"'";
                connection.result = connection.stat.executeQuery(query);
                
                connection.result.next();
                    
                output = (connection.result.getString("kode_kantor_cabang"));
                
                
                connection.stat.close();
                connection.result.close();
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error!!\n" + e.toString());
        }
        return output;
    }
    private void inputDriver() {
        Format formatter = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String tanggal = formatter.format(txttanggal_lahir.getDate());
        DBConnect connection = new DBConnect();
        try {
            String query = "insert into Driver values (?,?,?,?,?,?,?,?,?,?)";
            connection.pstat = connection.conn.prepareStatement(query);
            connection.pstat.setString(1, txtid_driver.getText());
            connection.pstat.setString(2, txtnama_driver.getText());
            connection.pstat.setString(3, txtAlamat.getText());
            connection.pstat.setString(4, tanggal);
            connection.pstat.setString(5, txtno_telepon.getText());
            connection.pstat.setString(6, txtEmail.getText());
            connection.pstat.setString(7, "Tidak aktif");
            connection.pstat.setString(8, "Aktif");
            connection.pstat.setString(9, getKodeKantorCabang(KantorCabang));
            connection.pstat.setString(10, getDeptID("Driver"));
            
            connection.pstat.executeUpdate();
            connection.pstat.close();
            JOptionPane.showMessageDialog(this,
                    "Data tersimpan");
            txtid_driver.setText("DRV-"+getLastID());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal!\n" + e.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtKantorCabang;
    private javax.swing.JLabel txtid_driver;
    private javax.swing.JTextField txtnama_driver;
    private javax.swing.JTextField txtno_telepon;
    private com.toedter.calendar.JDateChooser txttanggal_lahir;
    // End of variables declaration//GEN-END:variables
}
